# Prometheus Configuration for PlantUML Editor Monitoring
# 包括的なメトリクス収集設定

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'plantuml-editor'
    environment: 'development'

# Alertmanager設定
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# アラートルール読み込み
rule_files:
  - "alerts/*.yml"

# スクレイプ設定
scrape_configs:
  # Prometheus自身の監視
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 5s
    metrics_path: /metrics

  # PlantUMLアプリケーション
  - job_name: 'plantuml-app'
    static_configs:
      - targets: ['plantuml-app:8086']
    scrape_interval: 5s
    metrics_path: /metrics
    scrape_timeout: 10s
    honor_labels: true
    params:
      format: ['prometheus']

  # Node Exporter（システムメトリクス）
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 10s
    metrics_path: /metrics

  # cAdvisor（コンテナメトリクス）
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 10s
    metrics_path: /metrics

  # Grafana
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    scrape_interval: 30s
    metrics_path: /metrics

  # InfluxDB
  - job_name: 'influxdb'
    static_configs:
      - targets: ['influxdb:8086']
    scrape_interval: 30s
    metrics_path: /metrics

  # Elasticsearch
  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch:9200']
    scrape_interval: 30s
    metrics_path: /_prometheus/metrics

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 15s

  # Nginx
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    scrape_interval: 15s
    metrics_path: /nginx_status

  # K6負荷テスト結果
  - job_name: 'k6'
    static_configs:
      - targets: ['k6:6565']
    scrape_interval: 5s
    metrics_path: /metrics
    honor_labels: true

  # Blackbox Exporter（外部監視）
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://plantuml-app:8086
        - http://plantuml-app:8086/health
        - http://grafana:3000
        - http://allure-server:5050
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # アプリケーション固有メトリクス
  - job_name: 'plantuml-custom-metrics'
    static_configs:
      - targets: ['plantuml-app:8086']
    scrape_interval: 5s
    metrics_path: /api/metrics
    honor_labels: true
    relabel_configs:
      - source_labels: [__name__]
        regex: 'plantuml_.*'
        target_label: service
        replacement: 'plantuml-editor'

  # テスト実行メトリクス
  - job_name: 'test-metrics'
    static_configs:
      - targets: ['plantuml-app:8086']
    scrape_interval: 10s
    metrics_path: /api/test-metrics
    honor_labels: true
    params:
      format: ['prometheus']

# Remote Write設定（InfluxDB統合）
remote_write:
  - url: "http://influxdb:8086/api/v1/prom/write?db=prometheus"
    queue_config:
      max_samples_per_send: 1000
      batch_send_deadline: 5s
      min_shards: 1
      max_shards: 200

# Global設定の詳細
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s
  
  # 外部ラベル
  external_labels:
    cluster: 'plantuml-editor'
    environment: 'monitoring'
    region: 'local'
    team: 'development'
    
# ストレージ設定
storage:
  tsdb:
    retention: "30d"
    min_block_duration: "2h"
    max_block_duration: "25h"

# フィーチャーフラグ
feature_flags:
  - "promql-at-modifier"
  - "remote-write-receiver"