version: '3.8'

services:
  playwright:
    build:
      context: .
      dockerfile: Dockerfile.permanent
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=test
      - PLAYWRIGHT_BROWSERS_PATH=/ms-playwright
      - BASE_URL=http://host.docker.internal:8086
    networks:
      - test-network
    command: npm run test:all
    stdin_open: true
    tty: true

networks:
  test-network:
    driver: bridge