name: 🐛 バグ報告 / Bug Report
description: バグや不具合を報告する
title: "[Bug] "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 🐛 バグ報告

        バグを報告いただき、ありがとうございます。以下の情報を記入して、問題の解決にご協力ください。

  - type: textarea
    id: bug-description
    attributes:
      label: 🔍 バグの説明
      description: バグの詳細な説明を記入してください
      placeholder: どのような問題が発生していますか？
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: 🔄 再現手順
      description: バグを再現するための手順を記入してください
      placeholder: |
        1. '...'に移動
        2. '...'をクリック
        3. '...'までスクロール
        4. エラーが発生
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: ✅ 期待される動作
      description: 本来どのような動作をするべきかを記入してください
      placeholder: 本来であればこのように動作するはずです...
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: ❌ 実際の動作
      description: 実際にどのような動作をしているかを記入してください
      placeholder: 実際にはこのような動作をしています...
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: 🖥️ 環境情報
      description: バグが発生している環境の詳細情報
      placeholder: |
        - OS: [e.g. Windows 11, macOS 13.0, Ubuntu 20.04]
        - ブラウザ: [e.g. Chrome 118, Firefox 119, Safari 16.1]
        - Node.js バージョン: [e.g. 18.17.0]
        - アプリケーションバージョン: [e.g. v1.0.0]
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: 📎 追加情報
      description: エラーメッセージ、スクリーンショット、ログなどの追加情報
      placeholder: |
        エラーメッセージ:
        ```
        [エラーメッセージをここに貼り付け]
        ```

        その他の関連情報:
    validations:
      required: false

  - type: dropdown
    id: severity
    attributes:
      label: 🚨 重要度
      description: バグの重要度を選択してください
      options:
        - 低 (Low) - 軽微な問題
        - 中 (Medium) - 通常の問題
        - 高 (High) - 重要な問題
        - 緊急 (Critical) - アプリケーションが使用不可
      default: 1
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: 🧩 影響コンポーネント
      description: 問題が発生している機能・コンポーネントを選択してください
      options:
        - フロントエンド (Frontend)
        - バックエンド (Backend)
        - API
        - データベース (Database)
        - 認証 (Authentication)
        - UI/UX
        - パフォーマンス (Performance)
        - セキュリティ (Security)
        - その他 (Other)
      multiple: true
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: ✅ 確認事項
      description: 以下の項目を確認してください
      options:
        - label: 既存のIssueで同様の問題が報告されていないことを確認しました
          required: true
        - label: 最新バージョンで問題が発生することを確認しました
          required: true
        - label: 提供した情報は正確で完全です
          required: true

  - type: markdown
    attributes:
      value: |
        ---
        
        ### 📞 サポート情報
        
        - 🔗 [ドキュメント](https://github.com/your-org/plantuml-jp2en/wiki)
        - 💬 [ディスカッション](https://github.com/your-org/plantuml-jp2en/discussions)
        - 📧 [コミュニティ](mailto:support@yourproject.com)
        
        **ご報告いただき、ありがとうございます！**
        チームが迅速に対応いたします。